logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor: TRACE
server:
    port: 8091
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root123
        url: jdbc:mysql://localhost:3306/travel_agency_web_db?useSSL=false&createDatabaseIfNotExist=true
        username: root

        security:
            oauth2:
                resourceserver:
                    jwt:
    #  check this uri what needs to be changed
    #  https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html
                        issuer-uri: https://idp.example.com/issuer

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    servlet:
        multipart:
#            no restriction of the size
            max-file-size: -1
            max-request-size: -1

jwt:
    secret:
        key: 5A7234753778214125442A472D4A614E645267556B58703273357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E63526654

