logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor: TRACE
server:
    port: 8085
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root123
        url: jdbc:mysql://localhost:3306/travel_agency_web_db?useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
